"""empty message

Revision ID: 0624392c1c9e
Revises: f43f442addcd
Create Date: 2021-07-22 16:22:52.156420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0624392c1c9e'
down_revision = 'f43f442addcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'placeholder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('placeholder', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
