"""empty message

Revision ID: f43f442addcd
Revises: 1144b24b9b19
Create Date: 2021-07-22 16:05:17.427340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43f442addcd'
down_revision = '1144b24b9b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('placeholder', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'placeholder')
    # ### end Alembic commands ###
